package com.faultaddr.greendaoapp.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.faultaddr.greendaoapp.db.RecordDetail;

import com.faultaddr.greendaoapp.db.RecordDetailDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig recordDetailDaoConfig;

    private final RecordDetailDao recordDetailDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        recordDetailDaoConfig = daoConfigMap.get(RecordDetailDao.class).clone();
        recordDetailDaoConfig.initIdentityScope(type);

        recordDetailDao = new RecordDetailDao(recordDetailDaoConfig, this);

        registerDao(RecordDetail.class, recordDetailDao);
    }
    
    public void clear() {
        recordDetailDaoConfig.clearIdentityScope();
    }

    public RecordDetailDao getRecordDetailDao() {
        return recordDetailDao;
    }

}
